"""
Parser for Phase 7 student reports.

This module parses markdown student reports generated by Phase 7
and extracts structured data for quantitative analysis.

Input format (from Phase 7 generator.py):
    # Bedömning: Elev {student_id}

    ## Sammanfattning
    ...

    ## Detaljerade bedömningar

    ### Fråga Q01
    **{aspect}:** {symbol} **{points}p** - {comment}
    ...
    **TOTAL: {total}/{max}p**
    **→ Nästa steg:** {feedback}
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional

from ..constants.patterns import NEXT_STEP_LINE


class ParseError(Exception):
    """Error during parsing of student report."""
    pass


@dataclass
class AspectAssessment:
    """Single aspect assessment from a question."""
    name: str
    assessment: str  # "excellent" | "partial" | "missing" | "unknown"
    points: float
    max_points: Optional[float] = None
    symbol: str = ""
    comment: str = ""


@dataclass
class QuestionAssessment:
    """Assessment for a single question."""
    question_id: str
    aspects: List[AspectAssessment] = field(default_factory=list)
    total_points: float = 0.0
    max_points: float = 0.0
    next_step: str = ""


@dataclass
class ParsedReport:
    """Complete parsed student report."""
    student_id: str
    questions: List[QuestionAssessment] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)


# Regex patterns for parsing
PATTERNS = {
    # Header: # Bedömning: Elev TestElev01
    'student_id': re.compile(r'^#\s*Bedömning:\s*Elev\s+([A-Za-z0-9_]+)', re.MULTILINE),

    # Question header: ### Fråga Q01
    'question_header': re.compile(r'^###\s*Fråga\s+(Q\d+)', re.MULTILINE),

    # Aspect line: **Name:** ✓ **1.0p** - Comment
    # Note: The colon is INSIDE the bold (e.g., **Centrala begrepp:**)
    # Supports various symbols: ✓ ✗ ⚠ and text
    'aspect_line': re.compile(
        r'\*\*([^*:]+):\*\*\s*([✓✗⚠]+)?\s*\*\*(\d+[.,]?\d*)p\*\*\s*(?:-\s*(.+))?',
        re.IGNORECASE
    ),

    # Total line: **TOTAL: 1.5/2.0p**
    'total_line': re.compile(r'\*\*TOTAL:\s*(\d+[.,]?\d*)/(\d+[.,]?\d*)p\*\*', re.IGNORECASE),

    # Next step — shared pattern (RFC-029 §3.5)
    'next_step': NEXT_STEP_LINE,
}


def parse_float(value: str) -> float:
    """Parse float from string, handling Swedish locale (comma as decimal)."""
    return float(value.replace(',', '.'))


def detect_assessment(symbol: str) -> str:
    """Detect assessment level from symbol or text."""
    if not symbol:
        return "unknown"

    symbol = symbol.strip().lower()

    # Check for explicit text
    if "excellent" in symbol:
        return "excellent"
    if "partial" in symbol:
        return "partial"
    if "missing" in symbol:
        return "missing"

    # Check for symbols
    if '✓' in symbol:
        return "excellent"
    if '⚠' in symbol:
        return "partial"
    if '✗' in symbol:
        return "missing"
    if '-' in symbol:
        return "unknown"

    return "unknown"


def parse_question(question_id: str, content: str) -> QuestionAssessment:
    """
    Parse a single question section.

    Args:
        question_id: The question ID (e.g., "Q01")
        content: The markdown content for this question

    Returns:
        QuestionAssessment with parsed data
    """
    question = QuestionAssessment(question_id=question_id.strip())

    # Parse aspects
    for match in PATTERNS['aspect_line'].finditer(content):
        name = match.group(1).strip()
        symbol = match.group(2) or ""
        points_str = match.group(3)
        comment = match.group(4) or ""

        aspect = AspectAssessment(
            name=name,
            assessment=detect_assessment(symbol),
            points=parse_float(points_str),
            symbol=symbol.strip() if symbol else "",
            comment=comment.strip()
        )
        question.aspects.append(aspect)

    # Parse total
    total_match = PATTERNS['total_line'].search(content)
    if total_match:
        question.total_points = parse_float(total_match.group(1))
        question.max_points = parse_float(total_match.group(2))
    else:
        # Try to calculate from aspects if no total found
        if question.aspects:
            question.total_points = sum(a.points for a in question.aspects)

    # Parse next step
    next_match = PATTERNS['next_step'].search(content)
    if next_match:
        question.next_step = next_match.group(1).strip()

    return question


def parse_student_report(filepath: Path) -> ParsedReport:
    """
    Parse a Phase 7 student report markdown file.

    Args:
        filepath: Path to the student report file

    Returns:
        ParsedReport with all parsed data

    Raises:
        FileNotFoundError: If file doesn't exist
        ParseError: If file format is invalid
    """
    filepath = Path(filepath)

    if not filepath.exists():
        raise FileNotFoundError(f"Student report not found: {filepath}")

    content = filepath.read_text(encoding='utf-8')

    # Extract student ID
    student_match = PATTERNS['student_id'].search(content)
    if not student_match:
        raise ParseError(f"Could not find student ID in header: {filepath}")

    student_id = student_match.group(1)

    # Find all question sections
    questions: List[QuestionAssessment] = []

    # Split by question headers
    question_headers = list(PATTERNS['question_header'].finditer(content))

    for i, match in enumerate(question_headers):
        question_id = match.group(1)
        start_pos = match.end()

        # Find end position (next question or end of file)
        if i + 1 < len(question_headers):
            end_pos = question_headers[i + 1].start()
        else:
            end_pos = len(content)

        question_content = content[start_pos:end_pos]
        question = parse_question(question_id, question_content)
        questions.append(question)

    return ParsedReport(
        student_id=student_id,
        questions=questions,
        metadata={
            "source_file": str(filepath)
        }
    )
